apiVersion: apps/v1
kind: Deployment
metadata:
  name: toleration-4-deployment
  labels:
    app: toleration-4
spec:
  replicas: 3
  selector:
    matchLabels:
      app: toleration-4
  template:
    metadata:
      labels:
        app: toleration-4
    spec:
      containers:
      - name: k8s-demo
        image: amitvashist7/k8s-tiny-web
        imagePullPolicy: IfNotPresent
        ports:
        - name: node-port
          containerPort: 80
      toleration-4s:
      - key: "app"
        operator: "Equal"
        value: "myapp"
        effect: "PreferNoSchedule"
